region = "us-east-1"
instance_key_name = ""#"els-srch-vi-prod-key"
s3_tfstate_bucket_name = "puppet_bucket_test"
res_nameprefix = "els-srch-vi-"
pub_sn_netnumber = "23"
priv_sn_netnumber = "24"
pub_sn_netmask = "24"
priv_sn_netmask = "24"
